# 异常处理

格式：

```python
try:
    语句块
except 异常类型1:
    异常处理1
except 异常类型2:
    异常处理2
...
except:
    异常处理n
else:
    正常处理
finally:
    收尾工作
```

下面根据各关键字分点讨论：
1. `except`：当try中的语句块发生对应异常类型时，就会执行except中的异常处理语句块。常见的异常类型有：
    - RuntimeError
    - TypeError
    - NameError
2. `else`：当try中的语句块正常执行没有报错，则执行else中的语句块。依赖于try中代码块成功执行的代码都应该放到else中
3. `finally`：无论try中的语句块是否正常执行，在执行完try、except、else中的所有语句后都会执行finally中的语句块。但和直接写在try-except结构下面的其它语句相比，finally有两点不同：
    1. 即使try中的语句块导致了程序崩溃，仍然会先执行finally中的语句块
    2. 如果try中的语句块发生了except中没有提及的异常，也会先执行finally中的语句块，再报错

## 捕获异常

可以通过 `except Exception as e:` 来捕获所有异常类型，以实现异常的分类处理，或打印出该异常信息等功能，如：

```python
try:
    ...
except Exception as e:
    print("---异常---：", e)
```

## try语句中的return

当在函数中使用try-except结构时，尽量不要在try中return。如果在try中return，会发生如下结果：
1. else中的代码不会执行（try中已经return了）
2. finally中的代码会执行（善后工作必定执行）
3. 因为finally中的代码跟着执行了，如果finally中也写了return，实际return的值会从try中return的值变成finally中return的值
